version: '3.7'

services:
  postgres:
    container_name: postgres-db
    image: postgres:11.5
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'db'
    ports:
      - '5430:5432'
    restart: unless-stopped
